/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peps;

/**
 *
 * @author B
 */
public class InventarioFarmacia extends javax.swing.JFrame {

    /**
     * Creates new form InventarioFarmacia
     */
    public InventarioFarmacia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cmbMovimientoItem1 = new javax.swing.JComboBox<>();
        cmbMovimientoItem2 = new javax.swing.JComboBox<>();
        cmbMovimientoItem3 = new javax.swing.JComboBox<>();
        cmbMovimientoItem4 = new javax.swing.JComboBox<>();
        cmbMovimientoItem5 = new javax.swing.JComboBox<>();
        cmbMovimientoItem6 = new javax.swing.JComboBox<>();
        cmbMovimientoItem7 = new javax.swing.JComboBox<>();
        cmbMovimientoItem8 = new javax.swing.JComboBox<>();
        txtInventarioFinItem1 = new javax.swing.JTextField();
        txtInventarioFinItem2 = new javax.swing.JTextField();
        txtInventarioFinItem3 = new javax.swing.JTextField();
        txtInventarioFinItem4 = new javax.swing.JTextField();
        txtInventarioFinItem5 = new javax.swing.JTextField();
        txtInventarioFinItem6 = new javax.swing.JTextField();
        txtInventarioFinItem7 = new javax.swing.JTextField();
        txtInventarioFinItem8 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        txtMovimientoItem1 = new javax.swing.JTextField();
        txtMovimientoItem2 = new javax.swing.JTextField();
        txtMovimientoItem3 = new javax.swing.JTextField();
        txtMovimientoItem4 = new javax.swing.JTextField();
        txtMovimientoItem5 = new javax.swing.JTextField();
        txtMovimientoItem6 = new javax.swing.JTextField();
        txtMovimientoItem7 = new javax.swing.JTextField();
        txtMovimientoItem8 = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inventario PEPS Farmacia Despertad");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 71, 643, 10));

        jLabel1.setText("Farmacia Despertad");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 145, 25));

        jLabel2.setText("Producto");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 51, -1, -1));

        jLabel3.setText("Cantidad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 51, -1, -1));

        jLabel5.setText("Marca");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, -1, -1));

        jLabel6.setText("Unidades en inventario");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, -1, -1));

        jLabel7.setText("Acetaminofen");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 84, -1, -1));

        jLabel8.setText("Alcohol 90");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabel9.setText("Bacaolinita");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 141, -1, -1));

        jLabel10.setText("Cardio Aspirina");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 172, -1, -1));

        jLabel11.setText("Dolofin");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 203, -1, -1));

        jLabel12.setText("Gasas");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 241, -1, -1));

        jLabel13.setText("Suero");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 279, -1, -1));

        jLabel14.setText("Vick Vaporub");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        cmbMovimientoItem1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrada", "Salida" }));
        getContentPane().add(cmbMovimientoItem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));

        cmbMovimientoItem2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrada", "Salida" }));
        getContentPane().add(cmbMovimientoItem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        cmbMovimientoItem3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrada", "Salida" }));
        getContentPane().add(cmbMovimientoItem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, -1));

        cmbMovimientoItem4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrada", "Salida" }));
        getContentPane().add(cmbMovimientoItem4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, -1));

        cmbMovimientoItem5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrada", "Salida" }));
        getContentPane().add(cmbMovimientoItem5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));

        cmbMovimientoItem6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrada", "Salida" }));
        getContentPane().add(cmbMovimientoItem6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        cmbMovimientoItem7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrada", "Salida" }));
        getContentPane().add(cmbMovimientoItem7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));

        cmbMovimientoItem8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrada", "Salida" }));
        getContentPane().add(cmbMovimientoItem8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, -1, -1));
        getContentPane().add(txtInventarioFinItem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 75, -1));
        getContentPane().add(txtInventarioFinItem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 75, -1));
        getContentPane().add(txtInventarioFinItem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 75, -1));
        getContentPane().add(txtInventarioFinItem4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 75, -1));
        getContentPane().add(txtInventarioFinItem5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 75, -1));
        getContentPane().add(txtInventarioFinItem6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 75, -1));
        getContentPane().add(txtInventarioFinItem7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 75, -1));
        getContentPane().add(txtInventarioFinItem8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 75, -1));

        jLabel15.setText("MK");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, -1, -1));

        jLabel16.setText("Lab López");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, -1, -1));

        jLabel17.setText("Lab López");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, -1, -1));

        jLabel18.setText("Bayer");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, -1, -1));

        jLabel19.setText("Lab López");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, -1, -1));

        jLabel20.setText("MK");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, -1, -1));

        jLabel21.setText("Ancalmo");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, -1, -1));

        jLabel22.setText("Bayer");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, -1, -1));

        btnActualizar.setText("Actualizar datos");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, -1, 20));

        jLabel23.setText("Entrada o salida de inventario");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));
        getContentPane().add(txtMovimientoItem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 67, -1));
        getContentPane().add(txtMovimientoItem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 67, -1));
        getContentPane().add(txtMovimientoItem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 67, -1));
        getContentPane().add(txtMovimientoItem4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 67, -1));
        getContentPane().add(txtMovimientoItem5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 67, -1));
        getContentPane().add(txtMovimientoItem6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 67, -1));
        getContentPane().add(txtMovimientoItem7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 67, -1));
        getContentPane().add(txtMovimientoItem8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 67, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        int invInicio, invFin;
        if(cmbMovimientoItem1.getSelectedItem().toString() == "Entrada")
        {
            invInicio = Integer.parseInt(txtInventarioFinItem1.getText());
            invFin = invInicio + Integer.parseInt(txtMovimientoItem1.getText());
            txtInventarioFinItem1.setText(""+invFin);
        }
        else if(cmbMovimientoItem1.getSelectedItem().toString() == "Salida")
        {
            invInicio = Integer.parseInt(txtInventarioFinItem1.getText());
            invFin = invInicio - Integer.parseInt(txtMovimientoItem1.getText());
            txtInventarioFinItem1.setText(""+invFin);
        }
        if(cmbMovimientoItem2.getSelectedItem().toString() == "Entrada")
        {
            invInicio = Integer.parseInt(txtInventarioFinItem2.getText());
            invFin = invInicio + Integer.parseInt(txtMovimientoItem2.getText());
            txtInventarioFinItem2.setText(""+invFin);
        }
        else if(cmbMovimientoItem2.getSelectedItem().toString() == "Salida")
        {
            invInicio = Integer.parseInt(txtInventarioFinItem2.getText());
            invFin = invInicio - Integer.parseInt(txtMovimientoItem2.getText());
            txtInventarioFinItem2.setText(""+invFin);
        }
        if(cmbMovimientoItem3.getSelectedItem().toString() == "Entrada")
        {
            invInicio = Integer.parseInt(txtInventarioFinItem3.getText());
            invFin = invInicio + Integer.parseInt(txtMovimientoItem3.getText());
            txtInventarioFinItem3.setText(""+invFin);
        }
        else if(cmbMovimientoItem3.getSelectedItem().toString() == "Salida")
        {
            invInicio = Integer.parseInt(txtInventarioFinItem3.getText());
            invFin = invInicio - Integer.parseInt(txtMovimientoItem3.getText());
            txtInventarioFinItem3.setText(""+invFin);
        }
        if(cmbMovimientoItem4.getSelectedItem().toString() == "Entrada")
        {
            invInicio = Integer.parseInt(txtInventarioFinItem4.getText());
            invFin = invInicio + Integer.parseInt(txtMovimientoItem4.getText());
            txtInventarioFinItem4.setText(""+invFin);
        }
        else if(cmbMovimientoItem4.getSelectedItem().toString() == "Salida")
        {
            invInicio = Integer.parseInt(txtInventarioFinItem4.getText());
            invFin = invInicio - Integer.parseInt(txtMovimientoItem4.getText());
            txtInventarioFinItem4.setText(""+invFin);
        }
        if(cmbMovimientoItem5.getSelectedItem().toString() == "Entrada")
        {
            invInicio = Integer.parseInt(txtInventarioFinItem5.getText());
            invFin = invInicio + Integer.parseInt(txtMovimientoItem5.getText());
            txtInventarioFinItem5.setText(""+invFin);
        }
        else if(cmbMovimientoItem5.getSelectedItem().toString() == "Salida")
        {
            invInicio = Integer.parseInt(txtInventarioFinItem5.getText());
            invFin = invInicio - Integer.parseInt(txtMovimientoItem5.getText());
            txtInventarioFinItem5.setText(""+invFin);
        }
        if(cmbMovimientoItem6.getSelectedItem().toString() == "Entrada")
        {
            invInicio = Integer.parseInt(txtInventarioFinItem6.getText());
            invFin = invInicio + Integer.parseInt(txtMovimientoItem6.getText());
            txtInventarioFinItem6.setText(""+invFin);
        }
        else if(cmbMovimientoItem6.getSelectedItem().toString() == "Salida")
        {
            invInicio = Integer.parseInt(txtInventarioFinItem6.getText());
            invFin = invInicio - Integer.parseInt(txtMovimientoItem6.getText());
            txtInventarioFinItem6.setText(""+invFin);
        }
        if(cmbMovimientoItem7.getSelectedItem().toString() == "Entrada")
        {
            invInicio = Integer.parseInt(txtInventarioFinItem7.getText());
            invFin = invInicio + Integer.parseInt(txtMovimientoItem7.getText());
            txtInventarioFinItem7.setText(""+invFin);
        }
        else if(cmbMovimientoItem7.getSelectedItem().toString() == "Salida")
        {
            invInicio = Integer.parseInt(txtInventarioFinItem7.getText());
            invFin = invInicio - Integer.parseInt(txtMovimientoItem7.getText());
            txtInventarioFinItem7.setText(""+invFin);
        }
        if(cmbMovimientoItem8.getSelectedItem().toString() == "Entrada")
        {
            invInicio = Integer.parseInt(txtInventarioFinItem8.getText());
            invFin = invInicio + Integer.parseInt(txtMovimientoItem8.getText());
            txtInventarioFinItem8.setText(""+invFin);
        }
        else if(cmbMovimientoItem8.getSelectedItem().toString() == "Salida")
        {
            invInicio = Integer.parseInt(txtInventarioFinItem8.getText());
            invFin = invInicio - Integer.parseInt(txtMovimientoItem8.getText());
            txtInventarioFinItem8.setText(""+invFin);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventarioFarmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventarioFarmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventarioFarmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventarioFarmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventarioFarmacia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JComboBox<String> cmbMovimientoItem1;
    private javax.swing.JComboBox<String> cmbMovimientoItem2;
    private javax.swing.JComboBox<String> cmbMovimientoItem3;
    private javax.swing.JComboBox<String> cmbMovimientoItem4;
    private javax.swing.JComboBox<String> cmbMovimientoItem5;
    private javax.swing.JComboBox<String> cmbMovimientoItem6;
    private javax.swing.JComboBox<String> cmbMovimientoItem7;
    private javax.swing.JComboBox<String> cmbMovimientoItem8;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtInventarioFinItem1;
    private javax.swing.JTextField txtInventarioFinItem2;
    private javax.swing.JTextField txtInventarioFinItem3;
    private javax.swing.JTextField txtInventarioFinItem4;
    private javax.swing.JTextField txtInventarioFinItem5;
    private javax.swing.JTextField txtInventarioFinItem6;
    private javax.swing.JTextField txtInventarioFinItem7;
    private javax.swing.JTextField txtInventarioFinItem8;
    private javax.swing.JTextField txtMovimientoItem1;
    private javax.swing.JTextField txtMovimientoItem2;
    private javax.swing.JTextField txtMovimientoItem3;
    private javax.swing.JTextField txtMovimientoItem4;
    private javax.swing.JTextField txtMovimientoItem5;
    private javax.swing.JTextField txtMovimientoItem6;
    private javax.swing.JTextField txtMovimientoItem7;
    private javax.swing.JTextField txtMovimientoItem8;
    // End of variables declaration//GEN-END:variables
}
